# Generated by Django 5.0.6 on 2025-01-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_capture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capturedframe',
            name='image',
        ),
        migrations.AddField(
            model_name='capturedframe',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
